[unique-names-data]
git-tree-sha1 = "ab37cc50f6238c2dd0229176662711dfdb406eba"

    [[unique-names-data.download]]
    sha256 = "9ad9f2b6cd3bf56045a3faa2db6fd28fb0183defca4581bb4db6e0e109d536d9"
    url = "https://github.com/s-celles/unique-names-data/releases/download/v0.2.0/unique-names-data.tar.gz"
